apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend-service
  labels:
    app: task-manager-backend
    tier: backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: task-manager-backend
    tier: backend
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  sessionAffinity: None
