apiVersion: v1
kind: Service
metadata:
  name: task-manager-frontend-service
  labels:
    app: task-manager-frontend
    tier: frontend
    component: web
spec:
  type: ClusterIP
  selector:
    app: task-manager-frontend
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
